version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - logging
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.7.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
      - ./loki-data:/data/loki  # Make sure to mount the data directory properly
    networks:
      - logging

  promtail:
    image: grafana/promtail:2.7.0
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    networks:
      - logging
    depends_on:
      - loki

networks:
  logging:
    driver: bridge

