server:
  http_listen_port: 3100

# Configuring Loki to store logs locally
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
  filesystem:
    directory: /data/loki/chunks

schema_config:
  configs:
    - from: 2020-10-01
      store: boltdb_shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

# Limits and other configurations
limits_config:
  # Limiting the maximum number of entries per push request
  max_entries_per_push: 5000  # Correct field for controlling max entries per push

# Optionally you can add other fields like:
# - `max_line_size` (to control the maximum size of a single log line)
# - `max_streams_per_query` (to control the maximum number of streams that can be queried)

